//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPeState
{
    using System;
    using System.Collections.Generic;
    
    public partial class IC
    {
        public int IC_SK { get; set; }
        public int Investments_FK { get; set; }
        public int Contractors_FK { get; set; }
    
        public virtual Contractor Contractor { get; set; }
        public virtual Investment Investment { get; set; }
    }
}
